import type { GitHubConfig } from "../config/settings.js";
import type { GitHubReviewComment, GitHubReviewSubmission } from "../github/types.js";
import type { PRReview, ReviewComment, ReviewCommentSeverity } from "./types.js";

const SEVERITY_WEIGHT: Record<ReviewCommentSeverity, number> = {
    critical: 4,
    major: 3,
    minor: 2,
    suggestion: 1,
    praise: 0,
};

const REVIEW_DECISIONS: Record<PRReview["overallDecision"], GitHubReviewSubmission["event"]> = {
    approve: "APPROVE",
    request_changes: "REQUEST_CHANGES",
    comment: "COMMENT",
};

interface ReviewSubmissionOverrides {
    event?: GitHubReviewSubmission["event"];
}

export interface PreparedReviewSubmission {
    submission: GitHubReviewSubmission;
    inlineComments: GitHubReviewComment[];
    overflowComments: ReviewComment[];
}

export function shouldPostSeverity(
    severity: ReviewCommentSeverity,
    minSeverity: GitHubConfig["reviewPostMinSeverity"],
): boolean {
    if (severity === "praise") return false;
    return SEVERITY_WEIGHT[severity] >= SEVERITY_WEIGHT[minSeverity];
}

export function buildReviewBody(
    review: PRReview,
    overflowComments: ReviewComment[] = [],
): string {
    const lines = [
        "## AI Code Review",
        "",
        `**Decision**: ${review.overallDecision.replace(/_/g, " ").toUpperCase()}  |  **Risk Score**: ${review.riskScore}/10`,
        "",
        review.overallSummary,
    ];

    if (overflowComments.length > 0) {
        lines.push(
            "",
            "---",
            "",
            `### Additional Findings (${overflowComments.length})`,
            "",
            ...overflowComments.slice(0, 25).map(formatBodyFinding),
        );
    }

    lines.push(
        "",
        "---",
        `*Generated by [mygit](https://github.com/sorourf/MyGit) · ${review.modelUsed}*`,
    );

    return lines.join("\n");
}

export function collectCommentableRightSideLines(patch: string): Set<number> {
    const lines = new Set<number>();
    if (!patch.trim()) return lines;

    let currentNewLine = 0;
    for (const rawLine of patch.split("\n")) {
        if (rawLine.startsWith("@@")) {
            const match = rawLine.match(/\+(\d+)(?:,\d+)?/);
            currentNewLine = match ? parseInt(match[1], 10) : 0;
            continue;
        }
        if (rawLine.startsWith("+") || rawLine.startsWith(" ")) {
            lines.add(currentNewLine);
            currentNewLine += 1;
            continue;
        }
        if (rawLine.startsWith("-")) {
            continue;
        }
        if (rawLine.startsWith("\\")) {
            continue;
        }
        if (currentNewLine > 0) {
            lines.add(currentNewLine);
            currentNewLine += 1;
        }
    }

    return lines;
}

export function buildInlineReviewComments(
    review: PRReview,
    minSeverity: GitHubConfig["reviewPostMinSeverity"],
    filePatches: Record<string, string> = {},
): GitHubReviewComment[] {
    return prepareInlineCapableSubmission(review, minSeverity, filePatches).inlineComments;
}

export function prepareInlineCapableSubmission(
    review: PRReview,
    minSeverity: GitHubConfig["reviewPostMinSeverity"],
    filePatches: Record<string, string> = {},
    overrides: ReviewSubmissionOverrides = {},
): PreparedReviewSubmission {
    const eligible = review.comments.filter((comment) => shouldPostSeverity(comment.severity, minSeverity));
    const lineCache = new Map<string, Set<number>>();
    const inlineComments: GitHubReviewComment[] = [];
    const overflowComments: ReviewComment[] = [];

    for (const comment of eligible) {
        if (inlineComments.length >= 25) {
            overflowComments.push(comment);
            continue;
        }
        if (comment.line === undefined) {
            overflowComments.push(comment);
            continue;
        }

        const patch = filePatches[comment.filePath] ?? "";
        if (!lineCache.has(comment.filePath)) {
            lineCache.set(comment.filePath, collectCommentableRightSideLines(patch));
        }
        const validLines = lineCache.get(comment.filePath)!;
        if (!validLines.has(comment.line)) {
            overflowComments.push(comment);
            continue;
        }

        inlineComments.push({
            path: comment.filePath,
            line: comment.line,
            side: "RIGHT",
            body: buildCommentBody(comment),
        });
    }

    return {
        submission: {
            body: buildReviewBody(review, overflowComments),
            event: overrides.event ?? REVIEW_DECISIONS[review.overallDecision] ?? "COMMENT",
            comments: inlineComments.length > 0 ? inlineComments : undefined,
            commit_id: review.headSha,
        },
        inlineComments,
        overflowComments,
    };
}

export function prepareReviewSubmission(
    review: PRReview,
    minSeverity: GitHubConfig["reviewPostMinSeverity"],
    filePatches: Record<string, string> = {},
    overrides: ReviewSubmissionOverrides = {},
): PreparedReviewSubmission {
    return prepareInlineCapableSubmission(review, minSeverity, filePatches, overrides);
}

export function buildSummaryOnlySubmission(
    review: PRReview,
    minSeverity: GitHubConfig["reviewPostMinSeverity"] = "suggestion",
    overrides: ReviewSubmissionOverrides = {},
): GitHubReviewSubmission {
    return {
        body: buildReviewBody(
            review,
            review.comments.filter((comment) => shouldPostSeverity(comment.severity, minSeverity)),
        ),
        event: overrides.event ?? REVIEW_DECISIONS[review.overallDecision] ?? "COMMENT",
    };
}

export function buildBodyOnlySubmission(
    review: PRReview,
    minSeverity: GitHubConfig["reviewPostMinSeverity"] = "suggestion",
    overrides: ReviewSubmissionOverrides = {},
): GitHubReviewSubmission {
    return buildSummaryOnlySubmission(review, minSeverity, overrides);
}

export function shouldDowngradeRequestChangesForGitHub(error: unknown): boolean {
    const message = error instanceof Error ? error.message : String(error);
    const normalized = message.toLowerCase();
    return normalized.includes("can not request changes on your own pull request")
        || normalized.includes("cannot request changes on your own pull request");
}

export function buildCommentBody(c: ReviewComment): string {
    const lines: string[] = [
        `**[${c.severity.toUpperCase()}] ${c.title}**`,
        "",
        c.body,
    ];
    if (c.suggestion) {
        lines.push("", "**Suggestion:**", "```suggestion", c.suggestion, "```");
    }
    if (c.reasoningSteps.length > 0) {
        lines.push("", "<details><summary>Reasoning</summary>", "");
        for (const step of c.reasoningSteps) {
            lines.push(`- ${step}`);
        }
        lines.push("", "</details>");
    }
    return lines.join("\n");
}

function formatBodyFinding(comment: ReviewComment): string {
    const location = comment.line !== undefined
        ? `\`${comment.filePath}:${comment.line}\``
        : `\`${comment.filePath}\``;
    return [
        `- **[${comment.severity.toUpperCase()}] ${comment.title}** at ${location}`,
        `  ${comment.body}`,
    ].join("\n");
}
